=== JbRezidu/nouvellesTechnosRepartition/exo1/ExempleXML1/src/schemaXMLExemple1.xsd
<xs:schema  elementFormDefault="qualified" 
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns:bib="exemple1Test"
			targetNamespace="exemple1Test"
			xmlns="http://www.w3schools.com"
			>
  <xs:element name="bibliotheque">	  
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ouvrage" maxOccurs="unbounded" minOccurs="0">  
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="titre" minOccurs="1"/>
              <xs:element type="xs:string" name="auteur" maxOccurs="unbounded" minOccurs="1"/>
              <xs:element type="xs:string" name="editeur" minOccurs="1"/>
              <xs:element type="xs:int" name="prix" minOccurs="1"/>
              <xs:element name="refs" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="refLivre" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:int" name="isbn"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="ibsn"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="isbnKey" id="isbnKey">
	    <xs:selector xpath="ouvrage"/>
	    <xs:field xpath="@isbn"/>
	</xs:key>
	<xs:keyref name="refKey" refer="bib:isbnKey">
		<xs:selector xpath="ouvrage/refs/refLivre"/>
	  	<xs:field xpath="@isbn"/>
	</xs:keyref>
  </xs:element>
</xs:schema>

=== JbRezidu/nouvellesTechnosRepartition/exo1/ExempleXML1/src/exemple1.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliotheque xmlns="exemple1Test" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation="exemple1Test schemaXMLExemple1.xsd">
	<ouvrage ibsn="1234">
		<titre>ygyg</titre>
		<auteur>uhuhu</auteur>
		<editeur>ISTV</editeur>
		<prix>500</prix>
	</ouvrage>
	<ouvrage ibsn="2222">
		<titre>Jordane decu a la bu</titre>
		<auteur>Jordane</auteur>
		<editeur>BU</editeur>
		<prix>40</prix>
	</ouvrage>
	<ouvrage ibsn="3333">
		<titre>JB sur Skyrim</titre>
		<auteur>JB</auteur>
		<auteur>Jordane</auteur>
		<editeur>Steam</editeur>
		<prix>15</prix>
		<refs>
			<refLivre isbn="1234"/>
		</refs>
	</ouvrage>
	<ouvrage ibsn="4444">
		<titre>Livre de ref</titre>
		<auteur>Moit</auteur>
		<editeur>ISTV</editeur>
		<prix>10</prix>
		<refs>
			<refLivre isbn="1234"/>
			<refLivre isbn="2222"/>
		</refs>
	</ouvrage>
</bibliotheque>
